<?php require_once __DIR__.'/src/timeTracker.php'; ?>
<!DOCTYPE html>
<html>
<head>
    <script src='js/jquery-1.10.2.min.js'></script>
    <script src='js/timeTracker.js'></script>
    <script src="js/1.11.4jquery-ui.js"></script>
    <link rel="stylesheet" href="css/1.11.4jquery-ui.css">
    <!-- time picker -->
    <link href="js/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" type="text/css"/>
    <link rel="stylesheet" type="text/css" href="js/clockpicker/dist/bootstrap-clockpicker.min.css">
    <script type="text/javascript" src="js/clockpicker/dist/bootstrap-clockpicker.min.js"></script>
    <style>
        .input-group .form-control {
            z-index: 0;
        }
    </style>
</head>
<body>

<h1 style="text-align:center">Time Tracker</h1>
<form action="src/timeTrackerSubmit.php" method="post" enctype="multipart/form-data">
    <div class="projectheader">
        <select class="projectselector" name="0-project" >
            <option value=""></option>
            <?php foreach( $projectList as $project ){ ?>
                <option value="<?php echo $project ?>"><?php echo $project ?></option>
            <?php } ?>
        </select>
        <input class="ticketnumber" name="0-ticketnumber"/>
        <div class="ticketsummary"></div>
        <div>test mode: <input type="checkbox" name="0-test" value="true"></div>
        <div class="timertoggle play">play</div>
        <input type="submit" value="Submit">
    </div>
    <table>
        <tr class="current">
            <td>
                <input type="text" class="form-control date datepicker" value="" name="0-0-date" placeholder="date">
            </td>
            <td>
                <div class="input-group clockpicker">
                    <input type="text" class="start form-control" value="" name="0-0-start" placeholder="start">
                    <span class="input-group-addon">
                        <span class="glyphicon glyphicon-time"></span>
                    </span>
                </div>
            </td>
            <td>
                <div class="input-group clockpicker">
                    <input type="text" class="end form-control" value="" name="0-0-end" placeholder="end">
                    <span class="input-group-addon">
                        <span class="glyphicon glyphicon-time"></span>
                    </span>
                </div>
            </td>
            <td><input type="text" class='form-control duration' name="0-0-duration" placeholder="duration" readonly="readonly"></td>
            <td><input type="text" class='form-control description' name="0-0-description" placeholder="description"></td>
            <td>
                <select class="form-control type" name="0-0-type" placeholder="type">
                    <option value=""></option>
                </select>
            </td>
            <td>delete row</td>
        </tr>
    </table>
</form>

</body>
</html>
