<?php
// <p>---------------------------------------------------------</p>
// <p>          Error: Please allow phtml files to run php     </p>
// <p>---------------------------------------------------------</p>
require_once __DIR__ . '/../vendor/autoload.php';

// redirect to index.html if cookie not set and not using password verification
use Youtrackinterfacer\authenticationAndSecurity as authenticationAndSecurity;
$authenticationAndSecurity = new authenticationAndSecurity;
$authenticationAndSecurity->redirectIfNotLoggedIn();

require_once __DIR__ . '/code/getCustomSettings.php';
?>
<!DOCTYPE html>
<html>
<head>
    <script src='js/jquery-1.10.2.min.js'></script>
    <script type="text/javascript" src="js/bootstrap/bootstrap-3.3.7-dist/bootstrap.min.js"></script>
    <link rel="stylesheet" href="css/bootstrap/bootstrap-3.3.7-dist/bootstrap.min.css">
    <link rel="stylesheet" href="css/bootstrap/bootstrap-3.3.7-dist/bootstrap-theme.min.css">
</head>
<body>
    <header>
        <?php require_once(__DIR__ . '/header.phtml'); ?>
    </header>
    <form action="code/downloadFieldsSubmit.php" method="post" enctype="multipart/form-data">
        <h1 style="text-align:center">Youtrack custom field options and users csv</h1>
        <div>filename: <input type="text" name="filename"></div><br>
            <?php if ($authenticationType === 'password') : ?>
                <div>login user: <input type="text" name="user"></div><br>
                <div>login password: <input type="password" name="password"></div><br>
            <?php endif; ?>
        <input type="submit" value="Submit">
    </form>
</body>
</html>